// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoqxoyjgnqeewgssltdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcXhveWpnbnFlZXdnc3NsdGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDc5ODksImV4cCI6MjA1NzgyMzk4OX0.-6lE0FOnLhpsRSpfLx5fihsW_3yZMfH6ZdB5YyZ8EOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);